### ISSUE TITLE
Generated defaultValue for TIMESTAMP is `LocalDateTime.MIN`

### ISSUE THREAD

**Issue by davin111** [mscheong01/krotoDC#6]
It causes an exception like below.
```
java.lang.IllegalArgumentException: Timestamp is not valid. See proto definition for valid values. Seconds (-31557014135596800) must be in range [-62,135,596,800, +253,402,300,799]. Nanos (0) must be in range [0, +999,999,999].
	at org.curioswitch.common.protobuf.json.ProtobufUtil.checkValid(ProtobufUtil.java:420)
	at org.curioswitch.common.protobuf.json.ProtobufUtil.formatTimestamp(ProtobufUtil.java:84)
	at org.curioswitch.common.protobuf.json.WellKnownTypeMarshaller$TimestampMarshaller.doWrite(WellKnownTypeMarshaller.java:279)
	at org.curioswitch.common.protobuf.json.WellKnownTypeMarshaller$TimestampMarshaller.doWrite(WellKnownTypeMarshaller.java:257)
	at org.curioswitch.common.protobuf.json.WellKnownTypeMarshaller$WrapperMarshaller.writeValue(WellKnownTypeMarshaller.java:64)
	at org.curioswitch.common.protobuf.json.SerializeSupport.printMessage(SerializeSupport.java:219)
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller$ByteBuddy$diaKldbv.doWrite(Unknown Source)
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller$ByteBuddy$diaKldbv.doWrite(Unknown Source)
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.writeValue(TypeSpecificMarshaller.java:88)
```

I think it should be something like `com.google.protobuf.Timestamp.getDefaultInstance().toLocalDateTime()`.

Can I try to fix it?

**Comment by mscheong01** [comment]
This is indeed a bug, and [HandledPreDefinedTypes.kt](https://github.com/mscheong01/krotoDC/blob/main/generator/src/main/kotlin/io/github/mscheong01/krotodc/predefinedtypes/HandledPreDefinedType.kt) will have to be fixed. Also, contributions are always welcome 😆.
